### ISSUE TITLE
ORCA-387: Composer not loading plugins in tests

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#245]
**This issue needs to be resolved prior to July 2022 or ORCA tests are very likely to break.**

I think ORCA's idiosyncratic use of Composer is causing some sort of split-brain behavior. Check out these warnings:

- https://github.com/acquia/blt/runs/6680517732?check_suite_focus=true#step:8:27
- https://github.com/acquia/blt/runs/6680518383?check_suite_focus=true#step:6:28

> cweagans/composer-patches contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe. See https://getcomposer.org/allow-plugins
You can run "composer config --no-plugins allow-plugins.cweagans/composer-patches [true|false]" to enable it (true) or keep it disabled and suppress this warning (false)

> For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.

What's weird is that BLT, ORCA, and Drupal Minimal Project all whitelist those plugins. And indeed, running `composer install` or `composer validate` on any of those repos works fine. But if you run ORCA's vendor-local Composer you get the warning. My global and ORCA's local Composer version are both 2.3.5.

I suspect Composer is getting confused because it's being run as a Composer dependency itself, and this is causing some sort of split-brain behavior.

**Comment by secretsayan** [comment]
This issue has been addressed in https://github.com/acquia/orca/releases/tag/v3.20.0. Hence closing.
