### ISSUE TITLE
New Google Chrome version breaking tests

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#37]
ORCA instructs Travis CI to install the latest stable version of Google Chrome:
https://github.com/acquia/orca/blob/develop/example/.travis.yml#L29

It also instructs vaimo/binary-chromedriver to install Chromedriver 74:
https://github.com/acquia/orca/blob/develop/composer.json#L63

This is problematic because in general, the Chromedriver version needs to match the Google Chrome binary version. This just became a problem as Chrome 76 was released, and now BLT tests are all failing:
https://travis-ci.com/acquia/blt/jobs/220972346

**Comment by TravisCarden** [comment]
Thank you, @danepowell. This has been hotfixed: https://github.com/acquia/orca/releases/tag/v1.0.0-alpha21
