### ISSUE TITLE
ORCA PHPCS task can pass even with coding style issues

### ISSUE THREAD

**Issue by swichers** [acquia/orca#41]
It seems like there are certain scenarios that can cause the PHPCS task to pass despite there being coding errors in files.

**Given:**

https://git.drupalcode.org/project/media_acquiadam/blob/8.x-1.x/phpcs.xml.dist

In `media_acquiadam.module`:

```php
/**
 * Minimal example.
 *
 * @return bool
 */
function minimal_example() {
  return TRUE;
}
```

**Expected:**

```
~/P/m/d/m/c/media_acquiadam  $ composer run-script phpcs
> vendor/bin/phpcs
.........E 10 / 10 (100%)



FILE: ...m/docroot/modules/contrib/media_acquiadam/media_acquiadam.module
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 410 | ERROR | Description for the @return value is missing
----------------------------------------------------------------------

Time: 384ms; Memory: 18MB

Script vendor/bin/phpcs handling the phpcs event returned with error code 1
```

**Actual:**

```
> '/home/travis/build/acquia/orca/vendor/bin/phpcs' '-s' '/home/travis/build/acquia/media_acquiadam'

 // Logging results...    

> '/home/travis/build/acquia/orca/vendor/bin/phpcs' '-s' '--report=json' '--report-file=/home/travis/build/acquia/orca/var/phpcs.json' '/home/travis/build/acquia/media_acquiadam'
Time: 2.23 secs; Memory: 10MB
```

(And the build passes)

PHPCS _does_ detect some issues when running through ORCA. My initial guess is that this is related to acquia/coding-standards-php#1 since I do see `php` extensions being flagged, but not `module` extensions.

**Comment by TravisCarden** [comment]
You are correct, @swichers. This is an effect of https://github.com/acquia/coding-standards-php/issues/1, which has been fixed upstream and pulled into ORCA in https://github.com/acquia/orca/commit/714215e407410106ccd093822f27d6d5ef8b3adf. I'm planning a release sometime soon. Thanks, as always, for the report. :)
