### ISSUE TITLE
False positive due to php-compatibility check

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#48]
BLT is using a third-party library with a class member named `family()`. Unfortunately this causes php compatibility checker to choke as you can see in this commit/test:
https://github.com/acquia/blt/pull/3912/commits/788cd7b2ced6752cd8df3891ac695d3425363bcd
https://travis-ci.com/acquia/blt/builds/135137198

```
FILE: /Users/dane/packages/blt/src/Robo/Common/EnvironmentDetector.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 263 | ERROR | Extension 'fam' is removed since PHP 5.1
----------------------------------------------------------------------
```

This is due to the following sniff:
https://github.com/PHPCompatibility/PHPCompatibility/blob/develop/PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php

IMHO this sniff is way too aggressive, and should be using a more finely granular list of deprecated functions. But for now, the recommended way to work around this is to whitelist any false positives like this (as documented in the sniff).

Can ORCA whitelist `family`, or open an upstream issue with php compatibility? Whatever makes sense to you.

**Comment by TravisCarden** [comment]
Thanks for the report, @danepowell. Let me look into this.

**Comment by TravisCarden** [comment]
Sorry I haven't been able to act on this yet, @danepowell. I haven't forgotten about it, and I plan to get to it after I wrap up some urgent priorities.

**Comment by TravisCarden** [comment]
Obviously this didn't make its way onto the priorities list, @danepowell. Is it still an issue?

**Comment by danepowell** [comment]
Yeah it's still an issue, BLT has worked around it using `// phpcs:ignore` which isn't great.
https://github.com/acquia/blt/blob/12.2.0/src/Robo/Common/EnvironmentDetector.php#L162

**Comment by TravisCarden** [comment]
@danepowell I've excluded the problematic sniff in our coding standards library ^^. I'll leave this issue open until we make a release there and update to it here.

**Comment by danepowell** [comment]
I think this was released.
