### ISSUE TITLE
Submodules should not have their own composer.json

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#58]
Acquia Connector 8.x-1.x contains a submodule Acquia Search. ORCA fails if this submodule doesn't have its own composer.json:
```
[ERROR] Missing required ../acquia_connector/acquia_search/composer.json.
```

It seems this behavior is by design and was introduced in https://github.com/acquia/orca/commit/24ccaf346721272072f619edc3de91bd566a96e4

I couldn't find any context related to that vis a vis motivation.

My understanding is that Drupal submodules should _not_ have their own composer.json files, since Composer has no concept of sub-packages, nor does DrupalCI or a lot of other systems that could break if dependencies don't exist in the root composer.json.

I can't find a solid prescriptive reference for whether submodules should have their own composer.json or not, but it seems like the de facto standard at least is to not have them:
- [composer.json not needed in the sub module erl_paragraphs](https://www.drupal.org/project/entity_reference_layout/issues/3039962)
- [Composer dependencies for submodules should be added to parent composer.json](https://www.drupal.org/project/linkback/issues/2959975)
- [Composer dependencies for submodules should be added to parent composer.json](https://www.drupal.org/project/monolog/issues/2849886)

**Comment by danepowell** [comment]
Nevermind, I just found your comments in https://github.com/acquia/acquia_connector/pull/54 and https://backlog.acquia.com/browse/PF-1543, which indicate why submodules should have composer.json (apparently it's supported by Drupal packagist). That reasoning makes sense, and I agree it's the desired behavior.

It's just a bit annoying when developing on modules locally to not get all of the dependencies from a root-level `composer install`, but that's probably the lesser evil.

**Comment by TravisCarden** [comment]
It looks like you figured this out, @danepowell. [I've created an issue](https://github.com/acquia/coding-standards-php/issues/6) to move this test to [`acquia/coding-standards`](https://github.com/acquia/coding-standards-php) and document the rationale so others don't have to dig for it like you did. That issue contains a fuller explanation for now.

**Comment by danepowell** [comment]
Thanks for the follow-up!
