### ISSUE TITLE
ORCA should be writing db settings to ci.settings.php

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#60]
BLT detects and makes a distinction between CI and local environments. When run locally, it will load `local.settings.php` but _not_ `ci.settings.php`. When run in CI, it will load `ci.settings.php` but _not_ `local.settings.php`.

ORCA is usually run in a CI environment, therefore it should write its db settings to `ci.settings.php`. However, it instead writes to `local.settings.php`. This has worked until now because BLT erroneously detected some CI environments as local if `variables_order` was not set. That will change soon: https://github.com/acquia/blt/issues/4005

To ensure backwards compatibility, and also ensure that ORCA can be run both locally and in CI going forward, I think it should put db settings in both `local.settings.php` _and_ `ci.settings.php`.

**Comment by TravisCarden** [comment]
Wanna try again with `orca:develop`, @danepowell?

**Comment by danepowell** [comment]
No joy: https://travis-ci.com/acquia/blt/jobs/289959630#L1141

It looks like you attempt to write to `ci.settings.php` only if it already exists. But it doesn't exist by default with new BLT projects, you need to create it.

**Comment by TravisCarden** [comment]
Oh, that's _my responsibility_, is it? 😉 #62 adds that behavior. Do you have any insight into why the Acquia Pipelines job would be failing?
