### ISSUE TITLE
Missing packages if core version is a loose constraint

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#70]
I created a custom ORCA job with the following configuration: `ORCA_CUSTOM_FIXTURE_INIT_ARGS="--core=^9.0.0-alpha2 --sut-only"`

The test run failed because ORCA didn't download dev packages as expected due to the bug I describe in #67 . Basically in the fixture creator ORCA tries to cast `^9.0.0-alpha2` to a float which becomes `0` rather than something useful like `9`.

Is this a bug with ORCA, or a bug with how I'm using it? 😄 In other words, are "loose" core version constraints allowed, or must it be a specific version? If a specific version is required, it might be nice to validate the input as such so the user gets a clearer error message.

**Comment by TravisCarden** [comment]
Ah, thanks, @danepowell. I didn't anticipate anyone using a version range, but the command help for the `--core` argument says that it accepts "Any version string Composer understands". So this is technically a bug in ORCA. (Shh, don't tell anyone. 😉) I'm working on a fix. It's not quite as trivial as I first imagined.

**Comment by TravisCarden** [comment]
@danepowell the range (or "loose constraint") issue is now fixed. I've confirmed it with this test case:
```bash
orca fixture:init -f --bare --core=^8.8 --no-site-install
```
Your case, however (`^9.0.0-alpha2`), now blows up for different reasons. Let's see if we can work them out together.
