### ISSUE TITLE
[Feature Request] Allow warnings to pass phpcs

### ISSUE THREAD

**Issue by kaynenh** [acquia/orca#79]
The Content Hub module is currently failing phpcs with the following error (4 times):

```
 1 | WARNING | File appears to be minified and cannot be
   |         | processed (Internal.Tokenizer.Exception)
```
These warnings are generated from 2 minified css and 2 minified js files, so they are definitely not something we want phpcs even sniffing.

Could we change the severity of warnings so that they do not fail phpcs? Thanks for considering!

**Comment by kaynenh** [comment]
Removing minified css/js from code sniffing would also be enough to fix this, so this issue may be enough: https://github.com/acquia/orca/issues/63

**Comment by Raksha-Bharuka** [comment]
Closing this issue because it has been inactive.
