### ISSUE TITLE
Reasoning behind removing Behat support and how it affects BLT

### ISSUE THREAD

**Issue by moerazem** [acquia/orca#87]
Hi,

I noticed that Behat support was removed from Orca.
Can you clarify the reasoning behind this decision? As I searched for any roadmaps to clarify this and didn't find any.

Also, I'm wondering how will this affect BLT, since blt-project already has Behat.

Thanks.

**Comment by TravisCarden** [comment]
Thanks for the question, @moerazem. You're right that though the change itself was announced, the rationale was not explained. In short, it's a maintenance nightmare, and it just didn't provide much value as we saw it. I've added fuller explanation to the PR that actually removed it: #81. I appreciate you pointing this out to me.

This should have no impact on BLT whatsoever, which tests its own functionality and never used ORCA's Behat implementation to do so anyway. In other words, ORCA's removal of built-in Behat testing has nothing to do with BLT's Behat testing tools.

By the way, you're the first ORCA user I've heard from outside of Acquia. Thank you for contributing! I'd love to hear more sometime about how you use ORCA if you care to share. Thanks! 😃
